# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=4)),
                ('year', models.CharField(max_length=4)),
                ('numberOfTeams', models.IntegerField()),
                ('numberOfGames', models.IntegerField()),
                ('numberOfMatchdays', models.IntegerField()),
                ('currentMatchday', models.IntegerField()),
                ('lastUpdated', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Competitions',
                'verbose_name': 'Competition',
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('matchday', models.PositiveIntegerField()),
                ('goals_home', models.IntegerField(default=0)),
                ('goals_away', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Fixtures',
                'verbose_name': 'Fixture',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=4)),
                ('short_name', models.CharField(max_length=64)),
                ('squad_market_value', models.CharField(max_length=32)),
                ('crest_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'verbose_name': 'Team',
            },
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='api.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Competition'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='api.Team'),
        ),
    ]
