# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=4, null=True)),
                ('year', models.CharField(max_length=4)),
                ('numberOfTeams', models.IntegerField(null=True)),
                ('numberOfGames', models.IntegerField(null=True)),
                ('numberOfMatchdays', models.IntegerField(null=True)),
                ('currentMatchday', models.IntegerField(null=True)),
                ('lastUpdated', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Competitions',
                'verbose_name': 'Competition',
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('matchday', models.PositiveIntegerField(null=True)),
                ('goals_home', models.IntegerField(default=0, null=True)),
                ('goals_away', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fixtures',
                'verbose_name': 'Fixture',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=4, null=True)),
                ('short_name', models.CharField(max_length=64, null=True)),
                ('squad_market_value', models.CharField(max_length=32, null=True)),
                ('crest_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'verbose_name': 'Team',
            },
        ),
        migrations.CreateModel(
            name='TeamRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
            ],
            options={
                'verbose_name_plural': 'Team ranks',
                'verbose_name': 'Team rank',
            },
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='api.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='api.Competition'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='api.Team'),
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, through='api.TeamRank', to='api.Team'),
        ),
    ]
