# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, to='api.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
