# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrank',
            name='goalDifference',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamrank',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamrank',
            name='goalsAgainst',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamrank',
            name='playedGames',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamrank',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
