# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170506_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='currentMatchday',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='lastUpdated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='api.Competition'),
        ),
    ]
