# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170506_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='squad_market_value',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
