# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170506_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='league',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='numberOfGames',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='numberOfMatchdays',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='numberOfTeams',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
