# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170506_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='goals_away',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='goals_home',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='matchday',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
